sudo: required
language: java
jdk: oraclejdk8

services:
- docker

env:
  global:
  - secure: "lJgEygmOrX20oref0R/Pglh5uHVoXmjCWpWMSG1satYDQ1OwsN/v7aVstZojKoRD0G/HlG1REJdZ2GTaeRz4szbQzNo+TPZxoU6JWW9FLPt12q/WCqUKYXnA7ROn8vmbRYT9l6jTKSTbGMVvPsL0NhyeWKlHyXTCGFHbse4JpzQL57AjAfaxCkpMuUljTdAz42+bbtokSmB/3XY+95j0sSip0HJQi6smCjJrF5b09tulp7vaNXxlA0G/SN7Zzc78CIehce+LHYTTUM3femLrF+2un9PXfFRtzaNW6uZAgnAi3ngkSHjjHH02nMj+z66xhLY4veCat8FNlRjdjXG9UXW1VZYUb4uhUhnyOWHKHqYQrF/QGVLAcbqnMWZoslz+mCBVTrdbb8DHNjX4hAUaxcncVG6jgFosR3XUI/+CtKubyGMe10U74EEAV+hp+9SC+fcFvBjWfWvrM3KdKwvrwOu9qrYqfMxPNRI3ewd4De8lrLck4uxEppe9zdojnzUlZiWTogef92kfHvWn04+oH/PO1Srl5nh4K8r30iBAjzoCivbAYADablS65LCf3SNTx8SXGoT+0AirpiB0x7TqKO3JJ3eR75py9kntyj+mbUUln5huiHaEJ3scIlgPKaagqm5o4OrdNFLg6Qlb16JygESL4rvnbF+ydROQIJilhOE="
  - secure: "FQqO+mpvxjPthsCcxZHOxj5ihI6e8wbwpUU9gkp+8MlOqYFYfkEl+9YXNgbRMgr7KBz+I0EOPnh8yzi1q2C3e53Nx20sKzFO+Q4Ay2M3lDyoZG3R+vYjLQ31TowLetneiBjBWgMiTxeh5I19edehdG1pleZM/cZL15GJt76hWF9g1owFiDM9eMGYMJ+5E5NKdH/OFWClnt3cbbTFouY9XsfhE6r48rQ968sg68GNt0O3tQ+Yozq+xGeiH9M+0CisL5TLr5fmxcujKVfiLkzBDuekEvvmXX/x+4JONJFx02XHLQA50FNnpEE/th7X6k/svJD8U/yiQSNgxrQ35M7ZbidulnEVqbKiUAIMF2JivHjXeKFcgD5WEbgMpYmjIQkLN6NDJ4/j2bSwNg0sFErY/FerdZbnpqVz8rDmf/kXu9qe6r5/uiGtSaXywtO/fTY+Wkru0ePiOq8A9+lV+vCzSMySupmIiu6OQWPJtsNRQ48Y0HIGzvq6SKGnmdmoc1rPI3tXbyHjmVR5GprThaA0YtzWY8PdkxQG9X3pL05/57NqM74ZShDfwKSlZd9UHSoH0tUWXGkTdu9nTR5KX7OV27o0jQtGBUrqqx/iRiIeC+fPAbMfl6VNZw+el69DYlBIF3H6w11tF6gZgpPnVpKmAq51oLuJ6s0kEjyZe0LtnAI="
  - secure: "ANNkuktuvjngT6YKapiQFmgNaRz6Ow1NQ3nmE8FZbkoKeO0j64teSh9A+EVygv+wB2sIf5fEgxibZaujLYssU3WHS1BTSh0N8BE/twYnBYg7doz4yAB1J30+k4+05KGd2+rNhElk2m7/2Z2qSVF+37DTpHbhej7Im+N4e/7JU+DOmdMZ5kbXqDgKMMihyZU4OzmGolllwMWno50qWSop0V8Kvt79cGkBPDGmiSxMOhA9h9rKLkoDZI530wv/bRUPQfOT+fT/P8D5F37L3SR+JG7Xu16d8ahv1aQl5WYUz2NTnGLs8bueG/pLjpvmBvOkxuCRHoqKF3syRrUjMcseAf3xNhUxVPOKoxODoa8/28apmDlCXildbOEBARSEKy/XZa4DdGOKnq0Y0NL7hOb381Ji8LVmWf5mD+2s9hMI3VfFF46uvfOkY3zA5zGUBlOQ8NgrzxcBgrxX6DuXOun77wfGvXkwu8bidnWd5tKjr1N2w9xIOP8F1bAyGP4FQvru3U02W6sSXEQqVVrK9XVtudq+/NBV7tR0Z43k/Gp5l28HBML/6VZ2tGukJiV//T9Eeur+WOvujNou9FvJ/Mcqc4hCdGbbvFC9ZR7Cf93LAJiIvBKgGA7biLCJbBfd0P6VcgauRu5imYxYeWuZH2uD1XoW0E47jfF0SSLWxNd88UM="
  - secure: "O1t0hTdac9CArasVHvWuPOci2Jb/8Hqv3LbJiTSOJQ1V7csfXWuGMITJ9738qSrPyDoImeBcYCcoM/LSrBKPuAVeoet4/1Kp+jI6glaeieVKFYY/miL347av+EyxwWCB9zlW9wTmshXOod0nlpSWm3UMWwPMyeF6dk3dGDPyBJ31HTsBslObQ8mXngTJmEbqOvrWUZnt1vNZN7UCVKtODN6I0ZEh3T411SlONnN3oCemLgLiXfdOFavvNrJj3kLitQ+jwVj0H55G9fuvimRa9I83MMd3AsXO6LGTbcQuNJX3w0MncCXY0XRLJqv4GKPJFjShqk6VTCnvqiGTuUrRzpV5v6qx8/JAZhJmsHiAEmL6EnPHJedB24w4uBjcpror4nRaujPlw8dnhPWSMFE0aMk7LE351FL+a6vx7GZjf0IIcPmwEpv3Gt70bnS4novXpLeJTwkOMQ3dUx4Srt6wQcaIpksG5daiMuTAbLQsVGHKRizcKYCj3IgEbYjJe1qzO+m/oOH30/bCVhZaxx6u4TCq1ICensULR8PxsWHQpEg7WwRzmbV3YjwfUQpL8WYBZGaOuaFlO/Z4srKrKcLgXJ6OXduyannt04/3PQ8TG6lLTiX71TWfGCYrW/2t5cxCYQaER//TpJ26KAylB1wqdGofz7R2zlXj/Q/IphvkJ7E="
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "micropatel-github"
    token:
      secure: $SONAR_TOKEN


script:
- mvn clean install -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar


after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=patelmayurm/mycicd
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: micropatel