sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

env:
  global:
  - secure: "a/YE+oNYhLQPIu4WkqhGnuTW6/aXyd6uO98cDzn8zTb58oKS5HUGzAZIJSWFH7loTsC9vcSFVwlJo2MioJln6fzVnxRlxxi8lvkYPB0VN4xyCs7FCuU6VXu2FauhlIkr8WX7nPRxxEXJ1G1X1KgfYV+3iE6rNxDN9Up48jYIDnqDzACf7Ui0D9MuW40CCpwAQ6IjxRrSguP5i7KfQ54pd6drg5OQg7+nTg4OyyD/Eawy1a6kcvZJvXJPcNk5V+2nKog3SsoclowkcOg1Q3CPc6+VD613AufuHyTCLQxAPEpJREyWCKecz37M4YRFIHXmTay9lMag/lXZp67FkHlQaF8xEwfgmPXk8eU8ZglQnenGK+qm4UnIdFbab9DzU1LWPk8K4LdDpAfIuqbEYHHsdVIIWn3jP4psl+zilxcwd2jVpw3he5PcV5esrFxNmSJT4YQRhonYOTwbisRIVL1h8snmJ7jxSJMwuHXunYrSU3WryZPhrjhtoqXTTokpb7vGG3Uc6Gugq4YbWkxp3mSX47+OjI/4tsONksa20V2K7CNHK3Jtq45ztkGtQbrnG2yrML7relf+xnYNhZJy041+jl5QZQBa725qnzfPjLpSIajrnp9qYD1hj0qs66KUZ1nZTHHG3x4ZN7IKm1lhB1gluMjUlOPRP1Sm3ONT4lb/hhw="
  - secure: "dgH0cPu2NAJVNQZNBeQmOz/QlUla0JqrxkRbPY9FWIh7k5bpudVJESMrx8V9YSScklmevv+LAZc2hB05gcMSBmYi+T5WcqRr2nGi/DaN9bOMaEWS79lgcsIvPRW/tNtJp/BR1ltnVHcvvN/Rl/DKbBVg8WGJo97QnXugFh/mbnI0LK8CVWVRp/X1dhGrUSYew8NVn1biq5qWsBn+yZD/cIzrDFvP4jRMnRIXZA37+lIgZb84xMV28q9FKr6c5N+/YeWs3AM1AgZeN18maSmHcmxgJ9aGPq6D2+7xkBkpjgFLrIKX0fw+jLIXd8SYqMmu6jMZojIGWCmJ7CIa45xX0buaGkskj7ISpZ+hXX7hEgmIPqxV7hYIEBDegb6cx+Epo6gTQoc0XgS/pSdIxs+UHhCn2kixRFIDDzErWlQ4OAp6Uozkyl3awv03zYltlGKMUp3Wr3iEYppajmcBxroMYNaTy+7fdiaU+t6jdPHJvzos/rVB/CPi8nRFdv8DczuTgKPX/9kcvhELG1LnKLU/HDkxRXNDFKbHc+0ma/9qvomkryLU5yx89xcDstpA8lwwdag9AV0a0k1JXPxyg99mQ1q0DkdjZR9kIrr/JRmIv0Umiea2EVsqrRW+RP5Wt0kGE9V8zHOi39gWdj9UuUaVQh7CG8LoOj95WuHNK+elpCE="
  - secure: "APegr1ig3XoExUdb6OU4y45I42qxFthNTUcW4ns3Nq3eE8co7UPzGJxliX6nZh946c0yQQsoK6/DfcQU5XQz7MOEv9XMCApsYjVlNm53ppxYWjoINkvme5r1W9jSs/ekaGuAfy0I+TxF/jaX/QDjnuJKNNHckpCAQCBN0r0vh9mJwXxocBk6+YR7rRIZYPog4A7XbhsMfrdei0YTjeldRUDOQFXrsx7v6cjC4GgDneg4sAg+aLr2mv2mFUvTjSwI9HxDOFsKhWgYjrPafQIA7oa+VEt5k/HuDvBRnrKsUo/vyIRSG9swCdjExfvx2z9bQ5IipbR6OQ9vKjW+DpjlLoYUnOi8QIt5gdVDWLQuu4B2DOjCtmF8OJN1AF3N/TGDKYkpd/Fr1HrX+6aKZQmgAWGLNyoOI4klHu650nCvpW4lP4fJ4/CzlpR2zS1T21JCSiXzUKHpDj00fNCkVyvY3W75uaRfF4x9Ng6TQobczxCrR1jUhfTqxiwPe7UOlKX1+vZYXbWB7bssMl3kuaETanL8F8U/0cmZZaqQB80BuhW+6LUJPwMIAS5/i6Qr863j1yjYK92KkVTZx9/UdAe9U/dbBDb0bUfIirmgMlqLf0dQXZcS0cy1L7Uq/qP04KSjbuaRTCeMaARmNN5dbvLzwdxvT0UnGoFRMwVyIBM5rMo="
  - secure: "O1t0hTdac9CArasVHvWuPOci2Jb/8Hqv3LbJiTSOJQ1V7csfXWuGMITJ9738qSrPyDoImeBcYCcoM/LSrBKPuAVeoet4/1Kp+jI6glaeieVKFYY/miL347av+EyxwWCB9zlW9wTmshXOod0nlpSWm3UMWwPMyeF6dk3dGDPyBJ31HTsBslObQ8mXngTJmEbqOvrWUZnt1vNZN7UCVKtODN6I0ZEh3T411SlONnN3oCemLgLiXfdOFavvNrJj3kLitQ+jwVj0H55G9fuvimRa9I83MMd3AsXO6LGTbcQuNJX3w0MncCXY0XRLJqv4GKPJFjShqk6VTCnvqiGTuUrRzpV5v6qx8/JAZhJmsHiAEmL6EnPHJedB24w4uBjcpror4nRaujPlw8dnhPWSMFE0aMk7LE351FL+a6vx7GZjf0IIcPmwEpv3Gt70bnS4novXpLeJTwkOMQ3dUx4Srt6wQcaIpksG5daiMuTAbLQsVGHKRizcKYCj3IgEbYjJe1qzO+m/oOH30/bCVhZaxx6u4TCq1ICensULR8PxsWHQpEg7WwRzmbV3YjwfUQpL8WYBZGaOuaFlO/Z4srKrKcLgXJ6OXduyannt04/3PQ8TG6lLTiX71TWfGCYrW/2t5cxCYQaER//TpJ26KAylB1wqdGofz7R2zlXj/Q/IphvkJ7E="
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "micropatel-github"
    token:
      secure: $SONAR_TOKEN


script:
- mvn clean install -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar


after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=patelmayurm/mycicd
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - echo $IMAGE_NAME
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: micropatel