sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

env:
  global:
  - secure: "lJgEygmOrX20oref0R/Pglh5uHVoXmjCWpWMSG1satYDQ1OwsN/v7aVstZojKoRD0G/HlG1REJdZ2GTaeRz4szbQzNo+TPZxoU6JWW9FLPt12q/WCqUKYXnA7ROn8vmbRYT9l6jTKSTbGMVvPsL0NhyeWKlHyXTCGFHbse4JpzQL57AjAfaxCkpMuUljTdAz42+bbtokSmB/3XY+95j0sSip0HJQi6smCjJrF5b09tulp7vaNXxlA0G/SN7Zzc78CIehce+LHYTTUM3femLrF+2un9PXfFRtzaNW6uZAgnAi3ngkSHjjHH02nMj+z66xhLY4veCat8FNlRjdjXG9UXW1VZYUb4uhUhnyOWHKHqYQrF/QGVLAcbqnMWZoslz+mCBVTrdbb8DHNjX4hAUaxcncVG6jgFosR3XUI/+CtKubyGMe10U74EEAV+hp+9SC+fcFvBjWfWvrM3KdKwvrwOu9qrYqfMxPNRI3ewd4De8lrLck4uxEppe9zdojnzUlZiWTogef92kfHvWn04+oH/PO1Srl5nh4K8r30iBAjzoCivbAYADablS65LCf3SNTx8SXGoT+0AirpiB0x7TqKO3JJ3eR75py9kntyj+mbUUln5huiHaEJ3scIlgPKaagqm5o4OrdNFLg6Qlb16JygESL4rvnbF+ydROQIJilhOE="
  - secure: "dgH0cPu2NAJVNQZNBeQmOz/QlUla0JqrxkRbPY9FWIh7k5bpudVJESMrx8V9YSScklmevv+LAZc2hB05gcMSBmYi+T5WcqRr2nGi/DaN9bOMaEWS79lgcsIvPRW/tNtJp/BR1ltnVHcvvN/Rl/DKbBVg8WGJo97QnXugFh/mbnI0LK8CVWVRp/X1dhGrUSYew8NVn1biq5qWsBn+yZD/cIzrDFvP4jRMnRIXZA37+lIgZb84xMV28q9FKr6c5N+/YeWs3AM1AgZeN18maSmHcmxgJ9aGPq6D2+7xkBkpjgFLrIKX0fw+jLIXd8SYqMmu6jMZojIGWCmJ7CIa45xX0buaGkskj7ISpZ+hXX7hEgmIPqxV7hYIEBDegb6cx+Epo6gTQoc0XgS/pSdIxs+UHhCn2kixRFIDDzErWlQ4OAp6Uozkyl3awv03zYltlGKMUp3Wr3iEYppajmcBxroMYNaTy+7fdiaU+t6jdPHJvzos/rVB/CPi8nRFdv8DczuTgKPX/9kcvhELG1LnKLU/HDkxRXNDFKbHc+0ma/9qvomkryLU5yx89xcDstpA8lwwdag9AV0a0k1JXPxyg99mQ1q0DkdjZR9kIrr/JRmIv0Umiea2EVsqrRW+RP5Wt0kGE9V8zHOi39gWdj9UuUaVQh7CG8LoOj95WuHNK+elpCE="
  - secure: "APegr1ig3XoExUdb6OU4y45I42qxFthNTUcW4ns3Nq3eE8co7UPzGJxliX6nZh946c0yQQsoK6/DfcQU5XQz7MOEv9XMCApsYjVlNm53ppxYWjoINkvme5r1W9jSs/ekaGuAfy0I+TxF/jaX/QDjnuJKNNHckpCAQCBN0r0vh9mJwXxocBk6+YR7rRIZYPog4A7XbhsMfrdei0YTjeldRUDOQFXrsx7v6cjC4GgDneg4sAg+aLr2mv2mFUvTjSwI9HxDOFsKhWgYjrPafQIA7oa+VEt5k/HuDvBRnrKsUo/vyIRSG9swCdjExfvx2z9bQ5IipbR6OQ9vKjW+DpjlLoYUnOi8QIt5gdVDWLQuu4B2DOjCtmF8OJN1AF3N/TGDKYkpd/Fr1HrX+6aKZQmgAWGLNyoOI4klHu650nCvpW4lP4fJ4/CzlpR2zS1T21JCSiXzUKHpDj00fNCkVyvY3W75uaRfF4x9Ng6TQobczxCrR1jUhfTqxiwPe7UOlKX1+vZYXbWB7bssMl3kuaETanL8F8U/0cmZZaqQB80BuhW+6LUJPwMIAS5/i6Qr863j1yjYK92KkVTZx9/UdAe9U/dbBDb0bUfIirmgMlqLf0dQXZcS0cy1L7Uq/qP04KSjbuaRTCeMaARmNN5dbvLzwdxvT0UnGoFRMwVyIBM5rMo="
  - secure: "O1t0hTdac9CArasVHvWuPOci2Jb/8Hqv3LbJiTSOJQ1V7csfXWuGMITJ9738qSrPyDoImeBcYCcoM/LSrBKPuAVeoet4/1Kp+jI6glaeieVKFYY/miL347av+EyxwWCB9zlW9wTmshXOod0nlpSWm3UMWwPMyeF6dk3dGDPyBJ31HTsBslObQ8mXngTJmEbqOvrWUZnt1vNZN7UCVKtODN6I0ZEh3T411SlONnN3oCemLgLiXfdOFavvNrJj3kLitQ+jwVj0H55G9fuvimRa9I83MMd3AsXO6LGTbcQuNJX3w0MncCXY0XRLJqv4GKPJFjShqk6VTCnvqiGTuUrRzpV5v6qx8/JAZhJmsHiAEmL6EnPHJedB24w4uBjcpror4nRaujPlw8dnhPWSMFE0aMk7LE351FL+a6vx7GZjf0IIcPmwEpv3Gt70bnS4novXpLeJTwkOMQ3dUx4Srt6wQcaIpksG5daiMuTAbLQsVGHKRizcKYCj3IgEbYjJe1qzO+m/oOH30/bCVhZaxx6u4TCq1ICensULR8PxsWHQpEg7WwRzmbV3YjwfUQpL8WYBZGaOuaFlO/Z4srKrKcLgXJ6OXduyannt04/3PQ8TG6lLTiX71TWfGCYrW/2t5cxCYQaER//TpJ26KAylB1wqdGofz7R2zlXj/Q/IphvkJ7E="
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "micropatel-github"
    token:
      secure: $SONAR_TOKEN


script:
- mvn clean install -B
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar


after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=patelmayurm/mycicd
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - echo $IMAGE_NAME
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: micropatel